### ISSUE TITLE
Tags: move source into note + change names

### ISSUE THREAD

**Issue by ErwinKomen** [ErwinKomen/RU-lenten#30]
There are several different tag fields now.
Two of these tag fields should be merged.
This means:
1. `TagQsource` disappears, and its contents must be added into `TagQnote`
1. The listview Tools > Tags: source should disappear
1. The name "Keyword" should be changed into "Concept"
    1. The name of the table should change
    1. THe name displayed in the different views should change
    1. The listview Tools > Keywords should become Tools > Concepts
1. The name `TagQnote` should be changed into `TagQkeyword` 
    1. The Tools > Tags: note should also change into Tools > Tags: keyword

**Comment by PietroDelcorno** [comment]
OK
