### ISSUE TITLE
Tags: notes

### ISSUE THREAD

**Issue by ErwinKomen** [ErwinKomen/RU-lenten#31]
Add the `TagQnote` possibility to the following fields:
1. Table `Author`, field `information`
1. Table `Manuscript`, the **new** field called `information` (see issue #32 )

**Comment by ErwinKomen** [comment]
The `TagQnote` has been renamed into `TagKeyword`

**Comment by ErwinKomen** [comment]
Actions:
1. For `Author`:
    1. Add field `infotags`
    1. Add `mixed_tag_fields` to the model
    1. Add list of occurrances in `TagKeywordDetailView` method `add_to_context()`
    1. Add `AuthorAdminForm` with correct `TagTextarea` widget specification

**Comment by ErwinKomen** [comment]
Okay, I moved the `AuthorListView` to the new incorporated `BasicList` from the app `basic`.

**Comment by PietroDelcorno** [comment]
OK: New section info in Authors and Manuscript 
TODO for PI: Add tags there (geographical and religious orders)
