### ISSUE TITLE
Tags: add group field

### ISSUE THREAD

**Issue by ErwinKomen** [ErwinKomen/RU-lenten#34]
1. Add the field `group` to each of the `Tag` types
1. Default value: "general"
1. The user should be able to change the `group` in the _details view_ of the particular `TagKeyword` (or other tag type; note: TagKeyword was TagQnote)
1. Add the column `group` to the listview of TagNote (and other types)
1. Allow sorting on `group` in the listview
1. Allow filtering on `group` in the listview

**Comment by ErwinKomen** [comment]
As for (1): added `tgroup` to `Tag`. This is a FK to the new model `Tgroup`
As for (2): there is a function `get_default()` added to `Tgroup`. That should be used. It returns the 'general' Tgroup instance (or creates it if it doesn't exist).

**Comment by ErwinKomen** [comment]
Also:
- Add 'tgroup' to the detail views for the three `Tag` types
- Change the basis for `TagListView` to `BasicList` for better more uniform processing

**Comment by PietroDelcorno** [comment]
**Please change** default value: general ==> change it in: new 
(This will help me to know that I have still to put the keyword in a group, while I keep a group with the name general...)

For the rest, it seems me it works well!

TODO for PI: Think to ‘move’ into this system of tag groups what now was “tag: liturgical” and “tag: communicative”, so to simplify the tools to use.

**Comment by ErwinKomen** [comment]
Actions:
1. Changed 'general' to 'new' in `Tgroup`, method `get_default()`

**Comment by ErwinKomen** [comment]
The default value has now changed to **New**.
The tags that had group 'general' (lower case) have been changed into 'General' (upper case).
The search has now been made case-insensitive.
I also added a `before_save()` method to the Tgroup details view, so in the future it won't be possible to have both 'general' and 'General'.

**Comment by PietroDelcorno** [comment]
Ok, it works.
Good also the case-insensitive change - it think it helps.
