### ISSUE TITLE
Tag listviews: bug

### ISSUE THREAD

**Issue by ErwinKomen** [ErwinKomen/RU-lenten#35]
There is a bug in the TagNote, TagSource and other tag listviews.
Right now the button **Add a note tag** links to adding a **keyword**.
That should be changed to adding a note tag.

**Comment by ErwinKomen** [comment]
Okay, 'note tag' has now changed into keyword (and 'keyword' changed into concept).
But anyway: the bug has been fixed when the `TagList` views started taking `BasicList` as basis.

**Comment by PietroDelcorno** [comment]
OK
