### ISSUE TITLE
Edition: add 'list of sermons'

### ISSUE THREAD

**Issue by ErwinKomen** [ErwinKomen/RU-lenten#36]
1. Add the field `list of sermons` to the `Edition` table.
    1. Note: this is within the paratextual elements.
1. Make sure this field is editable and viewable

**Comment by ErwinKomen** [comment]
Okay, decyphering... Go to the Details view of Edition. This view has a button "Paratextual elements".  Next to "Table of contents" there should also be a field "List of sermons".

**Comment by ErwinKomen** [comment]
Okay, done this

**Comment by PietroDelcorno** [comment]
OK

TODO for PI: Check editions already described
