### ISSUE TITLE
Manuscript: listview changes

### ISSUE THREAD

**Issue by ErwinKomen** [ErwinKomen/RU-lenten#37]
Several changes to the listview of manuscript:
1. Add a column `Author` at the beginning (author of the collection)
1. Change column `Information` into column `name` (name of manuscript)
1. Add a column `Notes` that shows an asterisk when the new field `information` holds some text (comparable to the `Notes` column in the Edition listview)

**Comment by ErwinKomen** [comment]
Actions:
1. Added column 'author' at the beginning of the listview (collection author)
1. Change `Information` into `name` (of manuscript)
1. Added column `Notes`

**Comment by ErwinKomen** [comment]
Also adapted the Manuscript part in `admin.py`

**Comment by PietroDelcorno** [comment]
Ok visualization from Menu ==> Manuscript 

**Suggestion**: adding an indication if there is a link (*), so a “Link” as it is “Notes?”.

**Comment by ErwinKomen** [comment]
Not sure what is needed...
1. If there is a '*' sign in "Notes?", there should be: ... (a link?? to where? from where?)

**Comment by PietroDelcorno** [comment]
Perfect for the addition of author.
Would that be possible to have also in the overview of "Sermon collections" the indication link with * as we have now within the single description of a sermon collection?

**Comment by ErwinKomen** [comment]
I lost track. No idea what the last remark refers to. This issue is about the `Manuscript listview`. What part of the application is the remark exactly referring to? Listview or details view of Sermon/Collection/Manuscript/Edition?

**Comment by PietroDelcorno** [comment]
Apologies for my confusion. 
I meant, if we can have also in the Manuscript listview the indication "Link" with * for each entry (yet, this is a low urgency issue - and indeed, if it is complex, we can do without it)

**Comment by ErwinKomen** [comment]
Pietro, this was already there 7 days ago: a column named "Link?" with an asterisk *, when a manuscript contains a link.

Clearly I am missing something. Sorry about that. Can you be more specific?

**Comment by PietroDelcorno** [comment]
Mhhh... you are right! I was confused. What I asked is there!
