### ISSUE TITLE
Numbering of collection, edition, sermon

### ISSUE THREAD

**Issue by ErwinKomen** [ErwinKomen/RU-lenten#38]
The numbering of the collection, edition and sermon should be changed.

1. `SermonCollection`:
    1. textfield `idno` >> change into _numeric_ field
1. `Edition`: 
    1. textfield `code` >> do automatically on the basis of idno, collection
    1 add _numeric_ field `idno`
    1. foreign key to `SermonCollection`
1. `Sermon`:
    1. textfield `code` >> do automatically on the basis of sermon.idno, edition, collection
    1. add _numeric_ field `idno`
    1. foreign key to `SermonCollection`

**Comment by ErwinKomen** [comment]
As for (1), `SermonCollection`: change the `idno`  into _numeric_ field

**Comment by ErwinKomen** [comment]
As for (3), `Sermon`:
- Added numeric field `idno`
- DId a data-migration to extract this number
- Added an FK field to `Edition`
- Data-migration to make the link to the edition (if there)
- Double checked FK to `SermonCollection`
- Added function `get_code()`
- Adapted the listview for `Sermon`

**Comment by ErwinKomen** [comment]
TODO:
- Check all occurrances of `.code` to see if it is chosen correctly everywhere
- If all works fine: remove the field `code` from `Edition` and from `Sermon`
- Then double check again if all works fine.

**Comment by PietroDelcorno** [comment]
Here we still have some **issues**
- If in the section “Sermons” I select a “collection” (for instance “Quadragesimale Gemma fidei”) the **duplication/triplication** of the sermons re-appear – (I think it is our issue #43)
- If I visualize a “Collection” (for instance, the “Gemma fidei”) the **list of sermons** continues to appear as 1/10/11/12/13.../2/20/21/... 3/31...4/41... This is a problem, since it doesn’t allow to have an overview of the collection and of the flow of its contents

**Comment by ErwinKomen** [comment]
I think internally we've got it right now. Now the 'listviews inside detail views' need to be set correctly too. Let's take this per detail view:
1. `CollectionDetailsView`
    1. List of Sermons: order  by `'collection__idno', 'edition__idno', 'idno'`
    1. List of Manuscripts: no changes
    1. List of Editions: order by `'collection__idno', 'edition__idno'`
1. `SermonDetailsView`: no added listview
1. `EditionDetailsView`
    1. List of Consulting: no changes
1. `PublisherDetailsView`: no additional listview
1. `AuthorDetailsiew`
    1. List of ollections: order by  `'idno'`
1. `ConteptDetailsView`: no additional listview
1. `ManuscriptDetailsView`: no additional listview

**Comment by ErwinKomen** [comment]
SHould now all be fixed.

**Comment by PietroDelcorno** [comment]
Yes, it works.
