### ISSUE TITLE
Sermon: listview has too many entries

### ISSUE THREAD

**Issue by ErwinKomen** [ErwinKomen/RU-lenten#43]
There's a bug: the Sermon Listview has too many items. It shows 91 instead of 49.

Reason: there is one additional entry for each additional **topic**.

Resolution: create the listview on the basis of 'firsttopic' instead of on 'topics'

**Comment by PietroDelcorno** [comment]
OK

**Comment by ErwinKomen** [comment]
Okay, this worked. The listview now works correctly, showing **50** sermons
