### ISSUE TITLE
SermonCollection: details view problem

### ISSUE THREAD

**Issue by ErwinKomen** [ErwinKomen/RU-lenten#44]
> **Problem**: The visualization in “Sermon collection” now does not work properly (see for instance the collection “Quadragesimale virgilianum” (code 6). Instead of the “information” we need to have visualized the “Manuscript” (in this case: Assisi, Biblioteca del Sacro Convento, Fondo Antico, ms. 557, fol. 105r-138v), then the link (which might be only a yes/no info, with a *) and perhaps the indication whether there is something in the box “information” (again, not the content, by a yes/no indication, with a *). [On this, see also #37]
> So we have: Manuscript [text]; Link [yes/no]; Information [yes/no], which in this case would more or less result in:
> Assisi, Biblioteca del Sacro Convento, Fondo Antico, ms. 557, fol. 105r-138v ¦ * ¦ * ¦

EK: this concerns the "Mansucripts that contain this collection" part. Here the "Information" part is output as JSON instead of decoded.

**Comment by ErwinKomen** [comment]
Changed according to the above.

**Comment by PietroDelcorno** [comment]
Perfect
