### ISSUE TITLE
Edition: bug on add new

### ISSUE THREAD

**Issue by ErwinKomen** [ErwinKomen/RU-lenten#46]
when I go in edition, if I click on “Add a new edition” it crashes (message: Attribute error at /edition/view...). [Yet, I managed to add new editions, not from there but from each collection]

**Comment by ErwinKomen** [comment]
There was a line missing in the `EditionList` view definition:
> `basic_add = 'edition_add'`

**Comment by PietroDelcorno** [comment]
This bug is not really fixed (or there is another one). 
I can click add a new edition, it opens, but then when I add data there and I try to save them it crashes again (message: ValueError at /admin/seeker/edition/add/)

**Comment by ErwinKomen** [comment]
Double checking, and it's true. I get an error message:
> "<Edition: 1/->" needs to have a value for field "id" before this many-to-many relationship can be used.

Reason: when the `save()` method is called for the `Edition`, the 'firstpublisher' is being determined before an Edition has actually been made.

Anyway, it's fixed now.
