### ISSUE TITLE
TagDetails: context in list of sermons

### ISSUE THREAD

**Issue by ErwinKomen** [ErwinKomen/RU-lenten#51]
This relates to showing the 'context' in the list of sermons that is shown in the TagDetails view of e.g. TagKeyword.

1. In general it works well, but sometime it remains blank – see for instance “miracle”; “Jews”. 
1. Now it visualizes only a few words. If it is not too difficult, it would be useful to visualize a bit more of the context. For instance, for “avarice” it shows “and avarice), for this reason he is allowed to assault Jesus...”. While ideally, it would work better with a full sentence like: “Three temptations are the same used by Satan to overcome the humanity at the beginning (gluttony, vainglory and avarice), for this reason he is allowed to assault Jesus in this way”. [~~You’ll let~~ **Please let** me know if in order to do so I have to do something different in writing the summaries...]

**Comment by ErwinKomen** [comment]
As for (1): While the issue doesn't say so, I am guessing that this behaviour is unwanted. Please give an example where there **is** context, but it is **not** shown.

As for (2): the computer is **not** able to recognize **sentences**. It is right now only able to give context in terms of:
- a number of preceding and following _characters_
- a number of preceding and following _words_

**Comment by ErwinKomen** [comment]
If this is _not_ okay now, then we need a very precise mathemetical specification of which context must be included (and which not).

**Comment by PietroDelcorno** [comment]
For what concerns (1), I gave you two examples: Jews (see what happens, it does not show content for sermon 5/1/38); and miracle (see in sermon 5/1/40).

For what concerns (2) we have to think about it. At the moment, the visualization is rather confusing (with its division in three invisible columns...) but I understand the problem of the computer that has to consider numbers of characters. On that, perhaps we have to consider to change way to visualize things here. For instance, putting the topics of the sermon, its concepts and then the button "see context/hide context" to give access to the full summary/note. What do you think?

**Comment by ErwinKomen** [comment]
As for (1): I found the error. THere was a wrong condition in `tag_combine_html()`, in internal function `parts_to_string()`.

As for (2): I now take into account spaces (only break on spaces), which means that whole words are shown. This means the visualization is less confusing. As for full context: just click the cell and it will show full context.

**Comment by PietroDelcorno** [comment]
Perfect for (1).
Good for (2). This works better. I suggest to keep it in this way, while I am thinking other solutions.
