### ISSUE TITLE
Collection: bibliography field

### ISSUE THREAD

**Issue by ErwinKomen** [ErwinKomen/RU-lenten#52]
The model `SermonCollection` has a field 'bibliography' (**Info author and bibliography**).
The contents of this field are right now _only_ shown in the **edit** , not in the regular (details) **view** mode.

Is this correct, or should this field also be shown in the **view** mode?

**Comment by PietroDelcorno** [comment]
1) Rename the field as "bibliography" (we have now in the list of authors space for info on them).
2) Make it visible in view mode - I suggest to visualize it into the "General notes" section, between "Exempla" and "Notes".

**Comment by ErwinKomen** [comment]
Okay:
1. Changed the label of the field from 'Info author and bibliography' into 'Bibliography'
1. Added it in "General notes" between "Exempla" and "Notes"
