### ISSUE TITLE
Markdown: more fields

### ISSUE THREAD

**Issue by ErwinKomen** [ErwinKomen/RU-lenten#53]
Pietro:
> The possibility to use bold and italics works well in the section of the summary – please extend it to other sections (namely, notes in sermons and the different descriptive boxes in the section on collections, edition, authors, manuscript...). So that in each of these spaces it would be possible both to include keywords (now it is possible in some of them, but not all... for instance, not in the information about authors) and to use italics and bold.

Erwin (24/jun): Please be specific here. That means, fill in the full overview of where you would like this feature to be available. (Note: issue #49  resolved the bold/italics (markdown) for ‘notes’ in SermonCollection, Sermon, Edition.)

| Model            | Textfield     | Label                              | Bold/Italic | Tags | Tagtype          |
|------------------|---------------|------------------------------------|-------------|------|------------------|
| SermonCollection | bibliography  | Info author and bibliography       |             | no   |                  |
| SermonCollection | liturgical    | Relationship with liturgical texts | yes         | yes  | TagLiturgical    |
| SermonCollection | communicative | Communicative strategy             | yes         | yes  | TagCommunicative |
| SermonCollection | sources       | Sources quoted                     | yes         | yes  | TagKeyword       |
| SermonCollection | exempla       | Exempla                            | yes         | yes  | TagKeyword       |
| SermonCollection | notes         | Notes                              | yes         | yes  | TagKeyword       |
| Edition          | datecomment   | Comment on the date                |             |      |                  |
| Edition          | folia         | Number of folia                    |             |      |                  |
| Edition          | note          | Note                               | yes         | yes  | TagKeyword       |
| Edition          | frontpage     | Front page / title page            |             |      |                  |
| Edition          | prologue      | Prologue                           |             |      |                  |
| Edition          | dedicatory    | Dedicatory letter                  |             |      |                  |
| Edition          | contents      | Table of contents                  |             |      |                  |
| Edition          | sermonlist    | List of sermons                    |             |      |                  |
| Edition          | othertexts    | Other texts                        |             |      |                  |
| Edition          | images        | Images                             |             |      |                  |
| Edition          | fulltitle     | Full title                         |             |      |                  |
| Edition          | colophon      | Colophon                           |             |      |                  |
| Manuscript       | name          | Name                               |             |      |                  |
| Manuscript       | info          | Info on manuscript                 | yes         | yes  | TagKeyword       |
| Manuscript       | link          | Link (if available)                |             |      |                  |
| Sermon           | thema         | Thema                              |             |      |                  |
| Sermon           | divisionL     | Division (Latin)                   |             |      |                  |
| Sermon           | divisionE     | Division (English)                 |             |      |                  |
| Sermon           | summary       | Summary                            | yes         | yes  | TagKeyword       |
| Sermon           | note          | Note                               | yes         | yes  | TagKeyword       |

**Comment by ErwinKomen** [comment]
TO BE EDITED AND FILLED IN BY **PIETRO**:

| Model            | Textfield     | Label                              | Bold/Italic | Tags | Tagtype          |
|------------------|---------------|------------------------------------|-------------|------|------------------|
| SermonCollection | bibliography  | Info author and bibliography       |             | no   |                  |
| SermonCollection | liturgical    | Relationship with liturgical texts | yes         | yes  | TagLiturgical    |
| SermonCollection | communicative | Communicative strategy             | yes         | yes  | TagCommunicative |
| SermonCollection | sources       | Sources quoted                     | yes         | yes  | TagKeyword       |
| SermonCollection | exempla       | Exempla                            | yes         | yes  | TagKeyword       |
| SermonCollection | notes         | Notes                              | yes         | yes  | TagKeyword       |
| Edition          | datecomment   | Comment on the date                |             |      |                  |
| Edition          | folia         | Number of folia                    |             |      |                  |
| Edition          | note          | Note                               | yes         | yes  | TagKeyword       |
| Edition          | frontpage     | Front page / title page            |             |      |                  |
| Edition          | prologue      | Prologue                           |             |      |                  |
| Edition          | dedicatory    | Dedicatory letter                  |             |      |                  |
| Edition          | contents      | Table of contents                  |             |      |                  |
| Edition          | sermonlist    | List of sermons                    |             |      |                  |
| Edition          | othertexts    | Other texts                        |             |      |                  |
| Edition          | images        | Images                             |             |      |                  |
| Edition          | fulltitle     | Full title                         |             |      |                  |
| Edition          | colophon      | Colophon                           |             |      |                  |
| Manuscript       | name          | Name                               |             |      |                  |
| Manuscript       | info          | Info on manuscript                 | yes         | yes  | TagKeyword       |
| Manuscript       | link          | Link (if available)                |             |      |                  |
| Sermon           | thema         | Thema                              |             |      |                  |
| Sermon           | divisionL     | Division (Latin)                   |             |      |                  |
| Sermon           | divisionE     | Division (English)                 |             |      |                  |
| Sermon           | summary       | Summary                            | yes         | yes  | TagKeyword       |
| Sermon           | note          | Note                               | yes         | yes  | TagKeyword       |

**Comment by PietroDelcorno** [comment]
Model | Textfield | Label | Bold/Italic | Tags | Tagtype
-- | -- | -- | -- | -- | --
SermonCollection | bibliography | Info author and bibliography |   | no |  
SermonCollection | liturgical | Relationship with liturgical texts | yes | yes | **TagKeyword**
SermonCollection | communicative | Communicative strategy | yes | yes | **TagKeyword**
SermonCollection | sources | Sources quoted | yes | yes | TagKeyword
SermonCollection | exempla | Exempla | yes | yes | TagKeyword
SermonCollection | notes | Notes | yes | yes | TagKeyword
Edition | datecomment | Comment on the date | yes | yes | TagKeyword
Edition | folia | Number of folia |   |   |  
Edition | note | Note | yes | yes | TagKeyword
Edition | frontpage | Front page / title page | yes | yes | TagKeyword 
Edition | prologue | Prologue | yes | yes | TagKeyword  
Edition | dedicatory | Dedicatory letter | yes | yes | TagKeyword
Edition | contents | Table of contents | yes | yes | TagKeyword
Edition | sermonlist | List of sermons | yes | yes | TagKeywords
Edition | othertexts | Other texts | yes | yes | TagKeyword
Edition | images | Images | yes | yes | TagKeyword 
Edition | fulltitle | Full title | yes | yes | TagKeyword 
Edition | colophon | Colophon | yes | yes | TagKeyword 
Manuscript | name | Name |   |   |  
Manuscript | info | Info on manuscript | yes | yes | TagKeyword
Manuscript | link | Link (if available) |   |   |  
Sermon | thema | Thema |   |   |  
Sermon | divisionL | Division (Latin) | yes | yes | TagKeyword
Sermon | divisionE | Division (English) | yes | yes | TagKeyword  
Sermon | summary | Summary | yes | yes | TagKeyword
Sermon | note | Note | yes | yes | TagKeyword
**Author** | info | Info author | yes | yes | TagKeywords
**Publisher** | info | Info publisher | yes | yes | TagKeywords

**Comment by PietroDelcorno** [comment]
Hi Erwin.
I filled in the above table (hopefully in a clear way). 
Note two changes (marked in bold). 

1) I changed TagLiturgical and TagCommunicative in TagKeywords. Now that we have the possibility to subdivide in groups the Keywords I will make two groups there about these issues (one is already there: Liturgy and prayer, while that about communication I still have to create with a fitting name). This should make much easier to arrange things for me. 

2) I added at the end the info for author (we already have this) and for publisher (we discuss it in issue #63)

**Comment by ErwinKomen** [comment]
1. `Edition`:
    1. `datecomment`: 
        1. view: is part of `get_full_date()` - changed datecomment into get_datecomment_display there
        1. model: added m2m field `datecommenttags` (related name = `edition_datecommenttags`)
        1. model: Added line into `mixed_tag_fields`
    1. `frontpage`
        1. Changes in model: added m2m field, added line into `mixed_tag_fields`
        1. Changes in `EditionDetailsView`
    1. Same for: `prologue`, `decicatory`, `contents`, `sermonlist`, `othertexts`, `images`, `fulltitle`, `colophon`
1. `SermonCollection`: added according to the table
1. `Publisher`: added, taking into account #63 (publisher info)
1. `Manuscript`: no changes
1. `Author`: is already there, no changes
1. `Sermon`: **TODO**

**Comment by ErwinKomen** [comment]
One remains: `SermonCollection`, `bibliography`. See issue #52

**Comment by ErwinKomen** [comment]
I added `bibliography`, and also added it to the tag system
