### ISSUE TITLE
Space line

### ISSUE THREAD

**Issue by ErwinKomen** [ErwinKomen/RU-lenten#54]
Pietro:
> b)	How can we introduce a space line in the summary? (Now I just put a dash...) 

Erwin: 
1. the summary of which (collection, sermon, edition, ...??)
1. what is a space line?

**Comment by ErwinKomen** [comment]
If you mean a "blank line", then this can be done by adding `<br>` where the line needs to be.

Also note with respect to the markdown, that section headings can be created using #, ##, ### and so forth before the heading.
That is, a heading like `Pay attention` can be signalled:
`#### Pay attention`
And is rendered as:
#### Pay attention

**Comment by PietroDelcorno** [comment]
Yes, it was it.
You can close this issue
