### ISSUE TITLE
Sermon details: add author in view

### ISSUE THREAD

**Issue by ErwinKomen** [ErwinKomen/RU-lenten#55]
Pietro:
> d)	In the list of sermons, we have both the author and the collection, yet when then one select a specific sermon, there is Collection, Code ... since most of the collections have very similar titles and a used cannot remember by hard the codes, I suggest to introduce also here Author

Erwin:
1. Where exactly would you like to see the author? Is that in the Sermon details view, e.g. [here](https://lentensermons.cls.ru.nl/sermon/view/57/)?

**Comment by PietroDelcorno** [comment]
Yes, in sermon/view, above the line of the "collection" - so here: https://lentensermons.cls.ru.nl/sermon/view/1/ 

Author: Johannes Gritsch [Conrad Grütsch]
Collection: Quadraqesimale 
Code: 1/1/1
...

**Comment by ErwinKomen** [comment]
Okay, added it.
