### ISSUE TITLE
Keyword: Latin labelled in italics

### ISSUE THREAD

**Issue by ErwinKomen** [ErwinKomen/RU-lenten#57]
Pietro (5.f):
> Would that be possible to make the keywords labelled as Latin to appear automatically in italics? (Now I add in the texts the dashes in the summaries...)

**Comment by ErwinKomen** [comment]
This pertains to `TagKeyword` items of whom the `tgroup` field contains the term `Latin`.

1. Add a test method `get_style()` to `TagKeyword`
1. This calls a test method `is_latin()` of the `Tgroup`, which looks for the (capital sensitive) name 'Latin'
1. The viewing of the keywords takes place in `TagtextModel`, method `adapt_display()`
    1. But this part of the code is completely oblivious to the `TagKeyword` model
    1. The type **tag** should not only have a field **tagid**, but also a field **style** that can have the value **italic**
        1. Adapt `TagtextModel` method `process_tags()` to add the field `style` where possible

**Comment by ErwinKomen** [comment]
Okay, this works now.

**Comment by PietroDelcorno** [comment]
This is excellent, it works well. 
Can we apply it also to the taggroup "Title"?

**Comment by ErwinKomen** [comment]
See issue #65
