### ISSUE TITLE
Edition listview: layout

### ISSUE THREAD

**Issue by ErwinKomen** [ErwinKomen/RU-lenten#60]
Pietro (7):
> 7.	List of editions. I saw that you added the publishers: perfect. I suggest to use the same size of the font and enlarge this box, so that if there are two publisher both are visible.
>     a.	If I try the search function – it crashes

Erwin: please be more specific about the **crash**: where are you (list/details view of X/Y/Z), and what do you search for?

**Comment by PietroDelcorno** [comment]
If you fo to https://lentensermons.cls.ru.nl/edition/list and try to serch for author (e.g. Ferrer) this is the rusult:

![image](https://user-images.githubusercontent.com/65396747/85998684-6a5b5b00-ba0b-11ea-91dd-fccb9cdf52e5.png).

It seems instead that the reseach with the filters "collection" and "place" works

**Comment by ErwinKomen** [comment]
I looked into this and corrected it. Well spotted!
