### ISSUE TITLE
Sermon listview: layout (?)

### ISSUE THREAD

**Issue by ErwinKomen** [ErwinKomen/RU-lenten#62]
Pietro (9):
> List of sermons: 
> 1. code (issue of the numbers), liturgical day - issue of the order 
> 1. in the search function, is it possible to offer the “select” option, as for the collections?

Erwin: I understand request (2), but what is the request for (1) above exactly?

**Comment by PietroDelcorno** [comment]
About (1): when I wrote my notes, the sorting function with the liturgical days was not working (for instance T18/2 came before T16/5 or things like that). Now it works, so that problem is solved.

**Comment by ErwinKomen** [comment]
This works.
