### ISSUE TITLE
Publisher info

### ISSUE THREAD

**Issue by ErwinKomen** [ErwinKomen/RU-lenten#63]
Pietro (10):
> If it is not to complex, it might be useful to have the possibility to add also to the publishers some information (as it is for authors), so that I might add when he lived, where he worked... (yet, if it is complex, we can think about it also in future...).

Erwin: please explain **where** the user should be able to add (and view) this information. Which details/list view? Where in the order of other items for that details/list view? Which fields to be added exactly?

**Comment by PietroDelcorno** [comment]
In https://lentensermons.cls.ru.nl/publisher/list we have only the name and in publisher/view there is no space to add information. I would be useful to make it similar to author/view, which means two things: 
1) add a box for general information (so I guess you clal it "notes") as we have in https://lentensermons.cls.ru.nl/author/list. 
b) give in publishers/view (for instance https://lentensermons.cls.ru.nl/publisher/view/4/) the list of the sermon collections he published, as we have in author/view the list of his sermon collections  like for authors (see  https://lentensermons.cls.ru.nl/author/view/9/ )

**Comment by ErwinKomen** [comment]
I added (1): the general information (called 'information', as with author)

TODO: (2)

**Comment by ErwinKomen** [comment]
Done, works

**Comment by PietroDelcorno** [comment]
One problem and one request

Problem: publisher/view does not show all the data present in the database at the moment. For instance, for Anton Koberger (https://lentensermons.cls.ru.nl/publisher/view/4/ ) it result that he published collection nr 3, yet he published also three editions of collection nr 1 (see  https://lentensermons.cls.ru.nl/collection/view/1/ ).

Request: Please add below the list of collections also the list of editions ordening them by year of edition

**Comment by ErwinKomen** [comment]
1. **Problem**: Anton Koberger (4) published editions: 3, 34, 35, 37. These editions are _not_ in table `Sermon`. 
    1. The correct route should be SermonCollection >> Edition >> Publisher
    1. SO the right approach is `editions__publishers__id`
    1. Okay, works
1. **Request**: 
    1. Add list of editions - okay, similar to the list with collection details
    1. Order by year - that is first `date`, then `date_late`
