### ISSUE TITLE
First edition in collection view

### ISSUE THREAD

**Issue by PietroDelcorno** [ErwinKomen/RU-lenten#69]
In collection/view, the information about the "first edition" shows the wrong data. Instead of the city and the name of the publisher of the first edition it shows the name of the author.
See for instance the collation by Johannes Meder (https://lentensermons.cls.ru.nl/collection/view/7/), where as first edition it now reads "Johannes Meder 1495" insead of "Basel, Michael Furter, 1495".

**Comment by ErwinKomen** [comment]
This is view `CollectionDetailsView`, method `add_to_context()`.
The call is to a `SermonCollection` method called `get_firstedition()`
The latter method is not correct. Improved it. WOrks okay now.
