### ISSUE TITLE
Other bug - Collection list

### ISSUE THREAD

**Issue by PietroDelcorno** [ErwinKomen/RU-lenten#72]
I don't know if connected with issue 71, if I try to access from the menu List the Collection  (collection/list), it gives a message of error. I am pretty sure that two/three days ago it worked, so perhaps it is connected with issue 71 (yet, I leave it to you ;) ).
I checked, an the other lists of the menu work.

![image](https://user-images.githubusercontent.com/65396747/95556304-6af48c00-0a13-11eb-8503-97d8d51987d9.png)

**Comment by ErwinKomen** [comment]
Related to #71, and solved now
