### ISSUE TITLE
Collection: status

### ISSUE THREAD

**Issue by ErwinKomen** [ErwinKomen/RU-lenten#73]
Add and visualize different status field**s** to the `SermonCollection` model. If time left: also add it to the `Sermon` model.
All status fields are editable **manually**.

## Model changes

1. For `SermonCollection`: 
    1. One status field that indicates whether the list of sermons is complete: `status_sermons`
    1. One status field that indicates whether the list of editions is complete: `status_editions`
1. If time left: for `Sermon`:
    1. One status field that indicates completeness: `status_sermon`

The possible values of `status_...` are: 
- `com`: 'complete' (green)
- `pro`: 'in progress' (orange)
- `ini`: 'red' (default/initialization)
    

## Implications for detail views
> ... in case of https://lentensermons.cls.ru.nl/collection/view/13/ , I will have beside the writing “Sermons of this collection” a traffic light green (since the list is complete) and beside the “Printed editions that contain this collection” a traffic light green (the list is complete); while on https://lentensermons.cls.ru.nl/collection/view/1/ , I will have in the first case a traffic light orange (the list of the sermon is in progress) and for the “Printed editions” a traffic light green (the list is complete).

1. Make `status_sermons` and `status_editions` editable in the `SermonCollection` details view
2. If time left: make `status_sermon` editable in the `Sermon` details view

Note: the details **edit** view provides just a combobox where one of the three status values can be set. The details **view** view only shows the 'traffic light'. Hovering over the traffic light results in seeing the actual 'name' of the status.

## Implications for list views
> In https://lentensermons.cls.ru.nl/collection/list then show the two traffic lights. The traffic light about the status of the list of the sermon (1) can be put beside the code, that is between code and author. The one about whther the list of editions (2) is complete, can be beside the number of “editions” (see my rudimentary image).

![image](https://user-images.githubusercontent.com/11887269/116060948-9a52a980-a682-11eb-937c-d54999d0f882.png)

**Comment by ErwinKomen** [comment]
## Actions

1. Model: 
    1. Added fields `statussrm` and `statusedi` to `SermonCollection`
    2. Added FieldChoice PROGRESS_TYPE with values for status as defined above
    3. Server migration to process these changes
    4. Offline check of status field editability (see issue #74 for a suggestion)
1.

**Comment by PietroDelcorno** [comment]
Perfect.
In case we do also point 2 (sermon), it will need only one status field in sermon detail view. We will decide then where to show it in the sermon list view.

**Comment by ErwinKomen** [comment]
## Intermediate evaluation
1. What about the shape of the 'traffic lights'?
    1. Size
    2. Shape
1. Placement of the traffic lights
    1. For the details view
    2. For the listview
1. The popup explanations - are they okay?
1. The edit view allows setting the progress statuses manually - does that work as expected?

**Comment by PietroDelcorno** [comment]
1.1. Yes
1.2. Yes
2.1. Ok
2.2. Please, Expand the space of the area 'code' a bit, otherwise the 'traffic light' ends up to require another line (as in the image with the collection 10, 12 and following). There must be space for a number such as 245 + a space + "traffic light" 
![image](https://user-images.githubusercontent.com/65396747/116371245-838b8e80-a80b-11eb-9125-8a4f78eae06b.png)
3. Yes
4. Yes

**Comment by ErwinKomen** [comment]
Point 2.2: this is a browser-dependant thingy. 

Bootstrap class pull-right clashes with class `tdnowrap` (`white-space:nowrap !important;`) is set automatically for 'regular' columns of a listview in `BasicList` method `get_result_list()`. But that particular setting doesn't work for a combination of two spans within a `<td>`. 

An alternative to 'pull-right' is:
1. Have the parent <td> use style `max-width: nnnpx; display: flex;`
2. Set the 'margin-right' of the first <span> child:
```
td.flexsvg span:first-of-type {
    margin-right: auto;
}
```

This works for Chrome, and it doesn't clash with Firefox, so it should be okay.

## Note
The way to use this now is to add attribute `'flex': 'set'` in the `order_heads` definition of the corresponding listview.

**Comment by PietroDelcorno** [comment]
Not sure of what you suggests above. Yet, if the issue depends on the browser, I suggest (if it is not too difficult to do) to distinguish in list view between Code and Status, so that the latter will have its own space. In that case, we will have:

Code I **Status** I Author I Title ...

**Comment by PietroDelcorno** [comment]
I am saying it, since also now they appear on my computer (which use chrome) on two lines, which does not look very nice:
![image](https://user-images.githubusercontent.com/65396747/116381415-2b598a00-a815-11eb-9eac-0485e716f58e.png)

**Comment by ErwinKomen** [comment]
Try doing Ctrl + F5...

**Comment by ErwinKomen** [comment]
## Actions for **Sermon**

**Comment by PietroDelcorno** [comment]
> Chrome browser needs to be refreshed in order for the changes in CSS to take place.

I logged-in again, an refreshed twice Chrome, yet it does not change. It is always showing the "light" on a second line. 
So, perhaps adding status as an information separated from code might help (-->  code /  status / author)

**Comment by PietroDelcorno** [comment]
About Action for Sermons

1) Shall I assume from your message that you count to do it within the working time we discussed for the 'complete/in progress' system? Otherwise, please tell me the amount of work you did and the one you foresee for this second task.
2) The same system used for collection will work well also for sermon, so a way to indicate manually the status - which is what you say in "model" and "edit detail", if I understand.
3) IF I understand your last two issues are: where shall we visualize the 'traffic light' in details view and list view?
For detail view it can be beside the writing "Sermon details"
For list view, my suggestion is to introduce a column 'status' between 'code' and 'authors' - yet, please let me know if you think that it is better/easier to put it elsewhere.

**Comment by PietroDelcorno** [comment]
The problem with the collection view is solved.

**Comment by ErwinKomen** [comment]
Additional request:
> ... visualize the status of the sermon also in the list of sermons of the collection/view.
> ... add the symbol of sermon status beside the code of the sermon (as in the picture below)

![issue73](https://user-images.githubusercontent.com/11887269/116525718-180ff280-a8d9-11eb-854f-7189f64a369c.png)

**Comment by ErwinKomen** [comment]
As for the additional request:
1. Add style `flexsvg` also in **site.css**, but make sure to allow it to work on an overarching `<span>` element too
2. Adapt `CollectionDetailsView`, method `add_to_context()`: combine code + statussrm into one piece of HTML
3. Allow `get_statussrm_light()` as well as `get_ptype_light()` to process attributes **width** and **height** (default '20', but for this particular request: '16')
