### ISSUE TITLE
Collection: inline editing of Manuscript and Edition

### ISSUE THREAD

**Issue by ErwinKomen** [ErwinKomen/RU-lenten#74]
Right now the **edit** view of a (sermon) collection gives inline access to the associated Manuscripts and Editions. Those can be quite a few. And apparently that takes the computer a lot of time.

Suggestion:
- Remove the 'inline' editing for Manuscript and Edition **from within** (sermon) collection

All manuscripts and editions are still editable from their respective menu's.
It is a five minute thing to either switch this ability on or off right now.

**Comment by PietroDelcorno** [comment]
Perfect. If this improvement can be done easilly, please go ahead (I noted that opening the edit of collection can takes time)

**Comment by ErwinKomen** [comment]
Okay, I out-commented the line.
Note to self: this is in admin.py, `SermonCollctionAdmin`, line:
`# inlines = [ManuscriptInline, EditionInline]`
