### ISSUE TITLE
Space for instructions

### ISSUE THREAD

**Issue by ErwinKomen** [ErwinKomen/RU-lenten#78]
> I would do it as it is for _News_ (news/list), so that I can have a space where I can autonomously add information on several aspects. Useful to be allowed to introduce there also links. 
>
> (Now we have in extra a link that leads to: https://lentensermons.cls.ru.nl/instruction, yet there I cannot introduce any info)
>
> I suggest to have _instruction_ indicated in the main menu of the homepage, beside _list_ and _tools_.
>
> So I guess the actions are:
> a)	Move link https://lentensermons.cls.ru.nl/instruction to the homepage menu
> b)	Introduce the function: “add a new instruction” (as it is in news the function “add a new instruction”)
> c)	Allow to introduce there both texts and links
>

**Comment by ErwinKomen** [comment]
### Main actions
1. Move the 'instruction' menu item 
    1. Right now it is 
    2. The new place should be on the main menu of the homepage, (beside _list_ and _tools_)
1. Models: 
    1. Create a table `Instruction` 
    2. Additional backup of database
    3. Migrate database
1. Views: 
    1. Create a listview for `Instruction` items
    2. Make listview editable for `lenten_editor`
    3. Add a details view
    4. Add an edit view
    5. Make `Instruction` process **markdown** (including links)
1. Documentation/help
    1. Add explanation on how 'links' work in the markdown

**Comment by PietroDelcorno** [comment]
For what I see, the modification works well. You can close this issue.
