### ISSUE TITLE
Homepage: restyle

### ISSUE THREAD

**Issue by ErwinKomen** [ErwinKomen/RU-lenten#81]
1. Titling
    1. Title is okay
    1. Subtitle: 
        1. Text should be 'Search facilities to the main late medieval Lenten sermon collections'
        2. Note: _no full stop here – a bit bigger the font_
1. Menu 
    1. Move the ‘log in’ to the ‘extra’ - since it will be only to those working to the database. 
    1. Cancel the function ‘sign up’ (as we said when we talk with Henk, this make sense in Passim, not here). 
    1. Cancel the ‘learn more’ (we have it as about in ‘extra’, plus I put it now also in project, see below).
1. Page **Project**
    1. Some changes in text (see PDF)
1. Cancel all these information from the homepage – some are not necessary, the other will be more in the page ‘about’. I suggest to put instead an image taken from a sermon collection (or a medieval preacher). If this is possible, I send you a few options (even nicer if we can have a slideshow with three or four pictures – yet hardly necessary).
1. Rename ‘Extra’ as ‘More’. Once that one do not have to sing up, I imagine that the home page will show immediately the menus above, as it is now when one is logged in:
![image](https://user-images.githubusercontent.com/11887269/125268539-16ff3680-e308-11eb-8cf7-9dd95e38d81e.png)
    1. Instead of ‘lenten’ indicate it as ‘Home’.
    2. Put in a slightly bigger font: List/Tools/Instruction/More (as it is now ‘lenten’)

**Comment by ErwinKomen** [comment]
## Implementation
1. Titling: Changed subtitle and made the font size now to `larger`
1. Menu:
    1. k
    2. k
    3. k
1. Page **Project**
    1. k  
1. Canceling??
    1. k  
1. Renaming
    1. k

**Comment by PietroDelcorno** [comment]
1. Ok
2. Ok
3. What about the possibility to introduce an image? 
4. This needs to be considered in light of point 3. If we can have an image (or more than one) there on the right, I will change 'Start your research' and 'Get involved' either rewriting or putting them in the page 'about' (issue 82).
5. OK.
5.iii. I thought to open the database once we had re-organized the page 'about' - yet I do not see problems that it is already open now.

**Comment by ErwinKomen** [comment]
As for an **image**, yes it is certainly possible to have one (or more) images on the homepage or any other page.

**Comment by ErwinKomen** [comment]
ok
